#!/bin/sh

### BEGIN INIT INFO
# Provides:          nodeServer
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts node with the server.js file
# Description:       starts node for the monitoring using server.js
### END INIT INFO


case $1 in
start) start-stop-daemon --start --exec /opt/node/bin/node /home/pi/SmartHome/server/server.js --pidfile /var/run/nodejs_server.pid --make-pidfile --chdir /home/pi/SmartHome/server/ --background
       ;;
stop)  start-stop-daemon --stop --pidfile /var/run/nodejs_server.pid
       ;;
esac

exit 0
